// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesttDeployApiWithEFcoreAndDocker.Database;

#nullable disable

namespace TesttDeployApiWithEFcoreAndDocker.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TesttDeployApiWithEFcoreAndDocker.Database.Entities.Book", b =>
                {
                    b.Property<Guid>("BookGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookCode")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookGUID");

                    b.HasIndex("StudentGUID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("TesttDeployApiWithEFcoreAndDocker.Database.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentGUID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("TesttDeployApiWithEFcoreAndDocker.Database.Entities.Book", b =>
                {
                    b.HasOne("TesttDeployApiWithEFcoreAndDocker.Database.Entities.Student", "Student")
                        .WithMany("Book")
                        .HasForeignKey("StudentGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TesttDeployApiWithEFcoreAndDocker.Database.Entities.Student", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
